# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: findow API
  description: The window to all your financial transactions
  version: "1.0.0"
# the domain of the service
host: www.notonto.de
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /banks:
    get:
      summary: Banks
      description: |
        Search Bank
      parameters:
        - name: search
          in: query
          description: search string to find a bank
          required: true
          type: string
      tags:
        - Banks
      responses:
        200:
          description: An array of banks
          schema:
            type: array
            items:
              $ref: '#/definitions/Bank'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /transactions:
    get:
      summary: Transactions
      description: |
        Returns alls the transactions
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /accounts:
    get:
      summary: Accounts
      description: |
        Returns alls the user's accounts
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Accounts
      responses:
        200:
          description: An array of accounts
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Transaction:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Account:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Bank:
    type: object
    properties:
      bank_id:
        type: string
        description: Unique identifier for the bank
      name:
        type: string
        description: Name of the Bank
      bic:
        type: string
        description: BIC
      blz:
        type: string
        description: Bankleitzahl
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
