DROP TABLE FINDOW.TRANSACTIONS;

CREATE TABLE FINDOW.TRANSACTIONS (
   TX_ID SERIAL PRIMARY KEY NOT NULL,
   AMOUNT         MONEY NOT NULL,
   BOOKING_DATE TIMESTAMP NOT NULL,
   CATEGORY_ID SERIAL REFERENCES FINDOW.CATEGORIES
);



